# Generated by Django 2.2.7 on 2019-11-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(max_length=255)),
                ('odpA', models.CharField(max_length=255)),
                ('odpB', models.CharField(max_length=255)),
                ('odpC', models.CharField(max_length=255)),
                ('odpD', models.CharField(max_length=255)),
                ('poprawnaOdp', models.CharField(max_length=1)),
            ],
        ),
    ]
