# Generated by Django 2.2.7 on 2019-11-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('best_score', models.IntegerField(default=-1)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
